pharmacogenomicsManagement/Models/Drug.cs
using System;
using System.Collections.Generic;

namespace pharmacogenomicsManagement.Models
{
    public partial class Drug
    {
        public Drug()
        {
            DrugDescription = new HashSet<DrugDescription>();
        }

        public string AtcCode { get; set; }
        public string DrugName { get; set; }

        public ICollection<DrugDescription> DrugDescription { get; set; }
    }
}

pharmacogenomicsManagement/Controllers/DrugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using pharmacogenomicsManagement.Models;
using pharmacogenomicsManagement.Services;
using pharmacogenomicsManagement.ViewModel;

namespace pharmacogenomicsManagement.Controllers
{
    public class DrugController : Controller
    {
        private readonly IDrugRepository _DrugRepository;
        private readonly IDiplotypeRepository _DiplotypeRepository;
        private readonly IDrugDescriptionRepository _DrugDescriptionRepository;

        public DrugController(IDrugRepository _IDrugRepository, IDiplotypeRepository _IDiplotypeRepository, IDrugDescriptionRepository _IDrugDescriptionRepository)
        {
            _DrugRepository = _IDrugRepository;
            _DiplotypeRepository = _IDiplotypeRepository;
            _DrugDescriptionRepository = _IDrugDescriptionRepository;

        }

        public IActionResult Index()
        {
            var drugVM = new List<DrugViewModel>();
            var drugs = _DrugRepository.GetAll();

            if(drugs.Count()==0)
            {
                return View("Empty");
            }
            return View(_DrugRepository.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Drug model)
        {
            if (ModelState.IsValid)
            {
                _DrugRepository.Create(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

pharmacogenomicsManagement/Views/Drug/Create.cshtml
@model IEnumerable<pharmacogenomicsManagement.Models.Drug>

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DrugName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.DrugName)
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@item.AtcCode">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.AtcCode">Details</a> |
        <a asp-action="Delete" asp-route-id="@item.AtcCode">Delete</a>
    </td>
</tr>
}
    </tbody>
</table>

pharmacogenomicsManagement/Views/Drug/Empty.cshtml
<h2>No any drug available</h2>

pharmacogenomicsManagement/Views/Drug/Index.cshtml
@model IEnumerable<pharmacogenomicsManagement.Models.Drug>

<!--button-->
<a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Drug" asp-action="Create">Create new Drug</a>

<table class="table table-striped table-hover ">
    <thead>
        <!--tr代表標籤的意思-->
        <tr>
            <th>ATC code</th>
            <th>Drug Name</th>
            <th>View Detail</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.AtcCode</td>
            <td>@item.DrugName</td>
            <td><a class="btn btn-info" asp-area="" asp-controller="Pharmcogenome" asp-route-atccode="@item.AtcCode">View</a></td>
            <td><a class="btn btn-info" asp-area="" asp-controller="Drug" asp-action="Update" asp-route-id="@item.AtcCode">Edit</a></td>
            <td><a class="btn btn-danger" asp-area="" asp-controller="Drug" asp-action="Delete" asp-route-id="@item.AtcCode">Delete</a></td>
        </tr>
        }
    </tbody>
</table>